CREATE TABLE items (
    item_id SMALLINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    cost MEDIUMINT NOT NULL,
    class VARCHAR(30),
    INDEX idx_cost (cost),
    INDEX idx_class (class)
);

INSERT INTO items (name, cost, class)
VALUES ('ani-mines', 0, 'starter'),
    ('anima echo', 0, 'starter'),
    ('animapocalypse', 0, 'starter'),
    ('anti-shark sea mine', 0, 'starter'),
    ('bandle juice of haste', 1000, 'starter'),
    ('bandle juice of power', 1000, 'starter'),
    ('bandle juice of vitality', 1000, 'starter'),
    ('battle bunny crossbow', 0, 'starter'),
    ('battle cat barrage', 0, 'starter'),
    ('bearfoot chem-dispenser', 0, 'starter'),
    ('blade-o-rang', 0, 'starter'),
    ('bloodletter''s curse', 1250, 'starter'),
    ('bunny hop', 0, 'starter'),
    ('cull', 450, 'starter'),
    ('cyclonic slicers', 0, 'starter'),
    ('deep freeze', 0, 'starter'),
    ('doran''s blade', 450, 'starter'),
    ('doran''s ring', 400, 'starter'),
    ('doran''s shield', 450, 'starter'),
    ('double bun-bun barrage', 0, 'starter'),
    ('echoing batblades', 0, 'starter'),
    ('enveloping light', 0, 'starter'),
    ('evolved embershot', 0, 'starter'),
    ('explosive embrace', 0, 'starter'),
    ('fc limited express', 0, 'starter'),
    ('farsight alteration', 0, 'starter'),
    ('final city transit', 0, 'starter'),
    ('gatling bunny-guns', 0, 'starter'),
    ('grizzly smash', 0, 'starter'),
    ('guardian''s amulet', 250, 'starter'),
    ('guardian''s blade', 950, 'starter'),
    ('guardian''s hammer', 950, 'starter'),
    ('guardian''s horn', 950, 'starter'),
    ('guardian''s orb', 950, 'starter'),
    ('guardian''s shroud', 500, 'starter'),
    ('guiding hex', 0, 'starter'),
    ('gustwalker hatchling', 450, 'starter'),
    ('hellfire hatchet', 2500, 'starter'),
    ('hopped-up hex', 0, 'starter'),
    ('iceblast amor', 0, 'starter'),
    ('jinx''s tri-namite', 0, 'starter'),
    ('juice of haste', 500, 'starter'),
    ('juice of power', 500, 'starter'),
    ('juice of vitality', 500, 'starter'),
    ('kalista''s black spear', 0, 'starter'),
    ('light of the lion', 0, 'starter'),
    ('lightning braid', 3000, 'starter'),
    ('lioness''s lament', 0, 'starter'),
    ('lover''s ricochet', 0, 'starter'),
    ('meow meow', 0, 'starter'),
    ('mosstomper seedling', 450, 'starter'),
    ('neverending mobstomper', 0, 'starter'),
    ('oracle lens', 0, 'starter'),
    ('owo blaster', 0, 'starter'),
    ('paw print poisoner', 0, 'starter'),
    ('perplexity', 2500, 'starter'),
    ('pillory swipe', 0, 'starter'),
    ('prumbis''s electrocarver', 0, 'starter'),
    ('quad-o-rang', 0, 'starter'),
    ('radiant field', 0, 'starter'),
    ('rapid rabbit raindown', 0, 'starter'),
    ('rite of ruin', 2500, 'starter'),
    ('savage slice', 0, 'starter'),
    ('scorchclaw pup', 450, 'starter'),
    ('searing shortbow', 0, 'starter'),
    ('shield slam', 0, 'starter'),
    ('sin eater', 3000, 'starter'),
    ('sound wave', 0, 'starter'),
    ('statikk sword', 0, 'starter'),
    ('stealth ward', 0, 'consumable'),
    ('steel tempest', 0, 'starter'),
    ('sword of blossoming dawn', 2500, 'starter'),
    ('t.i.b.b.e.r.s.', 0, 'starter'),
    ('tear of the goddess', 400, 'starter'),
    ('tempest''s gauntlet', 0, 'starter'),
    ('tentacle slam', 0, 'starter'),
    ('the annihilator', 0, 'starter'),
    ('unceasing cyclone', 0, 'starter'),
    ('uwu blaster', 0, 'starter'),
    ('vayne''s chromablades', 0, 'starter'),
    ('vortex glove', 0, 'starter'),
    ('wandering storms', 0, 'starter'),
    ('winged dagger', 0, 'starter'),
    ('wordless promise', 2500, 'starter'),
    ('world atlas', 400, 'starter'),
    ('yuumibot', 0, 'starter'),
    ('control ward', 75, 'consumable'),
    ('corrupting potion', 500, 'consumable'),
    ('elixir of avarice', 50, 'consumable'),
    ('elixir of iron', 500, 'consumable'),
    ('elixir of sorcery', 500, 'consumable'),
    ('elixir of wrath', 500, 'consumable'),
    ('health potion', 50, 'consumable'),
    ('refillable potion', 150, 'consumable'),
    ('arcane sweeper', 0, 'distributed'),
    ('elixir of force', 50, 'distributed'),
    ('elixir of skill', 0, 'distributed'),
    ('enhanced lucky dice', 0, 'distributed'),
    ('eye of the herald', 0, 'distributed'),
    ('lucent singularity', 0, 'distributed'),
    ('lucky dice', 0, 'distributed'),
    ('minion dematerializer', 0, 'distributed'),
    ('mobility boots', 1000, 'distributed'),
    ('party favor', 0, 'distributed'),
    ('poro-snax', 0, 'distributed'),
    ('scouting ahead', 0, 'distributed'),
    ('slightly magical footwear', 300, 'distributed'),
    ('small party favor', 0, 'distributed'),
    (
        'total biscuit of everlasting will',
        50,
        'distributed'
    ),
    ('your cut', 0, 'distributed'),
    ('armored advance', 1700, 'boots'),
    ('berserker''s greaves', 1100, 'boots'),
    ('boots of swiftness', 1000, 'boots'),
    ('boots', 300, 'boots'),
    ('chainlaced crushers', 1750, 'boots'),
    ('crimson lucidity', 1400, 'boots'),
    ('forever forward', 1400, 'boots'),
    ('ghostcrawlers', 1000, 'boots'),
    ('ionian boots of lucidity', 900, 'boots'),
    ('mercury''s treads', 1250, 'boots'),
    ('plated steelcaps', 1200, 'boots'),
    ('sorcerer''s shoes', 1100, 'boots'),
    ('spellslinger''s shoes', 1600, 'boots'),
    (' swiftmarch ', 1500, ' boots '),
    (' symbiotic soles ', 900, ' boots '),
    (' amplifying tome ', 400, ' basic '),
    (' b.f.sword ', 1300, ' basic '),
    (' blasting wand ', 850, ' basic '),
    (' cloak of agility ', 600, ' basic '),
    (' cloth armor ', 300, ' basic '),
    (' dagger ', 250, ' basic '),
    (' dark seal ', 350, ' basic '),
    (' faerie charm ', 200, ' basic '),
    (' glowing mote ', 250, ' basic '),
    (' long sword ', 350, ' basic '),
    (' needlessly large rod ', 1200, ' basic '),
    (' null - magic mantle ', 400, ' basic '),
    (' pickaxe ', 875, ' basic '),
    (' rejuvenation bead ', 300, ' basic '),
    (' ruby crystal ', 400, ' basic '),
    (' sapphire crystal ', 300, ' basic '),
    (' aether wisp ', 900, ' epic '),
    (' bami '' s cinder ', 900, ' epic '),
    (' bandleglass mirror ', 900, ' epic '),
    (' blighting jewel ', 1100, ' epic '),
    (' bramble vest ', 800, ' epic '),
    (' catalyst of aeons ', 1300, ' epic '),
    (' caulfield '' s warhammer ', 1050, ' epic '),
    (' chain vest ', 800, ' epic '),
    (' crystalline bracer ', 800, ' epic '),
    (' executioner '' s calling ', 800, ' epic '),
    (' fated ashes ', 900, ' epic '),
    (' fiendish codex ', 850, ' epic '),
    (' forbidden idol ', 600, ' epic '),
    (' giant '' s belt ', 900, ' epic '),
    (' glacial buckler ', 900, ' epic '),
    (' haunting guise ', 1300, ' epic '),
    (' hearthbound axe ', 1200, ' epic '),
    (' hexdrinker ', 1300, ' epic '),
    (' hextech alternator ', 1100, ' epic '),
    (' kindlegem ', 800, ' epic '),
    (' kircheis shard ', 700, ' epic '),
    (' last whisper ', 1450, ' epic '),
    (' lifeline ', 1600, ' epic '),
    (' lost chapter ', 1200, ' epic '),
    (' negatron cloak ', 850, ' epic '),
    (' noonquiver ', 1300, ' epic '),
    (' oblivion orb ', 800, ' epic '),
    (' phage ', 1100, ' epic '),
    (' quicksilver sash ', 1300, ' epic '),
    (' rectrix ', 775, ' epic '),
    (' recurve bow ', 700, ' epic '),
    (' scout '' s slingshot ', 600, ' epic '),
    (' seeker '' s armguard ', 1600, ' epic '),
    (' serrated dirk ', 1000, ' epic '),
    (' sheen ', 900, ' epic '),
    (' spectre '' s cowl ', 1250, ' epic '),
    (' steel sigil ', 1100, ' epic '),
    (' synchronized souls ', 900, ' epic '),
    (' the brutalizer ', 1337, ' epic '),
    (' tiamat ', 1200, ' epic '),
    (' tunneler ', 1150, ' epic '),
    (' vampiric scepter ', 900, ' epic '),
    (' verdant barrier ', 1600, ' epic '),
    (' warden '' s mail ', 1000, ' epic '),
    (' watchful wardstone ', 1100, ' epic '),
    (' winged moonplate ', 800, ' epic '),
    (' zeal ', 1200, ' epic '),
    (' abyssal mask ', 2650, ' legendary '),
    (' anathema '' s chains ', 2500, ' legendary '),
    (' archangel '' s staff ', 2900, ' legendary '),
    (' ardent censer ', 2200, ' legendary '),
    (' atma '' s reckoning ', 2900, ' legendary '),
    (' axiom arc ', 2750, ' legendary '),
    (' banshee '' s veil ', 3000, ' legendary '),
    (' black cleaver ', 3000, ' legendary '),
    (' blackfire torch ', 2800, ' legendary '),
    (
        ' blade of the ruined king ',
        3200,
        ' legendary '
    ),
    (
        ' bloodletter '' s curse full ',
        2900,
        ' legendary '
    ),
    (' bloodsong ', 400, ' legendary '),
    (' bloodthirster ', 3400, ' legendary '),
    (' bounty of worlds ', 400, ' legendary '),
    (' celestial opposition ', 400, ' legendary '),
    (' chempunk chainsword ', 3100, ' legendary '),
    (' cosmic drive ', 3000, ' legendary '),
    (' cryptbloom ', 3000, ' legendary '),
    (' dawncore ', 2500, ' legendary '),
    (' dead man '' s plate ', 2900, ' legendary '),
    (' death '' s dance ', 3300, ' legendary '),
    (' deathfire grasp ', 2900, ' legendary '),
    (' dream maker ', 400, ' legendary '),
    (' echoes of helia ', 2200, ' legendary '),
    (' eclipse ', 2900, ' legendary '),
    (' edge of night ', 3000, ' legendary '),
    (' essence reaver ', 2900, ' legendary '),
    (' experimental hexplate ', 3000, ' legendary '),
    (' fimbulwinter ', 2400, ' legendary '),
    (' force of nature ', 2800, ' legendary '),
    (' frozen heart ', 2500, ' legendary '),
    (' frozen mallet ', 3000, ' legendary '),
    (' guardian angel ', 3200, ' legendary '),
    (' guinsoo '' s rageblade ', 3000, ' legendary '),
    (' gunmetal greaves ', 1600, ' legendary '),
    (' heartsteel ', 3000, ' legendary '),
    (' hextech gunblade ', 3250, ' legendary '),
    (' hextech rocketbelt ', 2650, ' legendary '),
    (' hollow radiance ', 2800, ' legendary '),
    (' horizon focus ', 2750, ' legendary '),
    (' hubris ', 3000, ' legendary '),
    (' hullbreaker ', 3000, ' legendary '),
    (' iceborn gauntlet ', 2900, ' legendary '),
    (' immortal shieldbow ', 3000, ' legendary '),
    (' imperial mandate ', 2250, ' legendary '),
    (' infinity edge ', 3450, ' legendary '),
    (' innvervating locket ', 2950, ' legendary '),
    (
        ' jak '' sho,
            the protean ',
        3200,
        ' legendary '
    ),
    (' kaenic rookern ', 2900, ' legendary '),
    (' knight '' s vow ', 2300, ' legendary '),
    (' kraken slayer ', 3000, ' legendary '),
    (' liandry '' s torment ', 3000, ' legendary '),
    (' lich bane ', 2900, ' legendary '),
    (
        ' locket of the iron solari ',
        2200,
        ' legendary '
    ),
    (
        ' lord dominik '' s regards ',
        3100,
        ' legendary '
    ),
    (' luden '' s companion ', 2750, ' legendary '),
    (' malignance ', 2700, ' legendary '),
    (' manamune ', 2900, ' legendary '),
    (' maw of malmortius ', 3100, ' legendary '),
    (' mejai '' s soulstealer ', 1500, ' legendary '),
    (' mercurial scimitar ', 3200, ' legendary '),
    (' mikael '' s blessing ', 2300, ' legendary '),
    (' moonstone renewer ', 2200, ' legendary '),
    (' morellonomicon ', 2850, ' legendary '),
    (' mortal reminder ', 3300, ' legendary '),
    (' muramana ', 2900, ' legendary '),
    (' nashor '' s tooth ', 2900, ' legendary '),
    (' navori flickerblade ', 2650, ' legendary '),
    (' opportunity ', 2700, ' legendary '),
    (' overlord '' s bloodmail ', 3300, ' legendary '),
    (' phantom dancer ', 2650, ' legendary '),
    (' profane hydra ', 2850, ' legendary '),
    (' rabadon '' s deathcap ', 3500, ' legendary '),
    (' randuin '' s omen ', 2700, ' legendary '),
    (' rapid firecannon ', 2650, ' legendary '),
    (' ravenous hydra ', 3300, ' legendary '),
    (' redemption ', 2300, ' legendary '),
    (' riftmaker ', 3100, ' legendary '),
    (' rod of ages ', 2600, ' legendary '),
    (' runaan '' s hurricane ', 2650, ' legendary '),
    (' runic compass ', 400, ' legendary '),
    (
        ' rylai '' s crystal scepter ',
        2600,
        ' legendary '
    ),
    (' seraph '' s embrace ', 2900, ' legendary '),
    (' serpent '' s fang ', 2500, ' legendary '),
    (' serylda '' s grudge ', 3000, ' legendary '),
    (' shadowflame ', 3200, ' legendary '),
    (' shield of the rakkor ', 2675, ' legendary '),
    (
        ' shurelya '' s battlesong ',
        2200,
        ' legendary '
    ),
    (' solstice sleigh ', 400, ' legendary '),
    (' spear of shojin ', 3100, ' legendary '),
    (' spectral cutlass ', 2800, ' legendary '),
    (' spirit visage ', 2700, ' legendary '),
    (' staff of flowing water ', 2250, ' legendary '),
    (' statikk shiv ', 2700, ' legendary '),
    (' sterak '' s gage ', 3200, ' legendary '),
    (' stormrazor ', 3100, ' legendary '),
    (' stormsurge ', 2800, ' legendary '),
    (' stridebreaker ', 3300, ' legendary '),
    (' sundered sky ', 3100, ' legendary '),
    (' sunfire aegis ', 2700, ' legendary '),
    (' sword of the divine ', 2300, ' legendary '),
    (' terminus ', 3000, ' legendary '),
    (' the collector ', 3000, ' legendary '),
    (' thornmail ', 2450, ' legendary '),
    (' titanic hydra ', 3300, ' legendary '),
    (' trailblazer ', 2400, ' legendary '),
    (' trinity force ', 3333, ' legendary '),
    (' umbral glaive ', 2500, ' legendary '),
    (' unending despair ', 2800, ' legendary '),
    (' vigilant wardstone ', 2300, ' legendary '),
    (' void staff ', 3000, ' legendary '),
    (' voltaic cyclosword ', 3000, ' legendary '),
    (' warmog '' s armor ', 3100, ' legendary '),
    (' winter '' s approach ', 2400, ' legendary '),
    (' wit '' s
        end ', 2800, ' legendary '),
    (' youmuu '' s ghostblade ', 2800, ' legendary '),
    (' yun tal wildarrows ', 3000, ' legendary '),
    (
        ' zaz '' zak '' s realmspike ',
        400,
        ' legendary '
    ),
    (' zeke '' s convergence ', 2200, ' legendary '),
    (' zhonya '' s hourglass ', 3250, ' legendary ');
